### PR TITLE
fix https://github.com/alibaba/macaca/issues/271

### LINKED ISSUE #271: macaca安卓版本每次跑脚本都会安装输入法跟unlock软件
- **Macaca Version**:
- **Macaca Doctor Logs**:
- **Operate System**:
- **Programming Language**:

目前发现一款手机，估计是手机厂商权限设置，无论安装什么软件都会提示安装，需要手工人为点击同意，这样就造成了每次跑脚本的时候都再次安装macaca输入法和解锁unlock软件，都要人为操作后才能继续，能否在安装前先检查是否已经安装输入法和解锁软件，如果已经安装则不再安装呢？

### PR DESCRIPTION
**Pull request by CodeToSurvive1**
fix https://github.com/alibaba/macaca/issues/271

### CODE REVIEW

**Comment by xudafeng** [comment]
@CodeToSurvive1 容我仔细看看

File: lib/macaca-adb.js [hunk 1]
```diff
@@ -239,6 +239,32 @@ ADB.prototype.isScreenLocked = function() {
...
+
+  var promise = new Promise((resolve, reject) => {
+    this.shell(cmd).then(data => {
+      resolve(_.parseApkVersion(data));
+    }).catch(err => {
+      reject(`get installed apk version code failed with ${err}`);
+    });
+  });
+
+  if (args.length>1) {
```
Comment (xudafeng) [inline lib/macaca-adb.js]: style

File: lib/macaca-adb.js [hunk 2]
```diff
@@ -239,6 +239,32 @@ ADB.prototype.isScreenLocked = function() {
...
+    var cb = args[1];
+
+    promise.then(data => {
+      cb.call(this, null, data);
+    }).catch(function(err) {
+      cb.call(this, `kill process ${name} error with: ${err}`);
```
Comment (xudafeng) [inline lib/macaca-adb.js]: name 哪里来的？
